### ISSUE TITLE
有个问题请教一下，word2vec中<UNK>的矩阵是怎么计算出来的呀，谢谢

### ISSUE THREAD

**Issue by OYE93** [zjy-ucas/ChineseNER#1]

**Comment by molyswu** [comment]
python train.py 
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from loader import load_data
  File "/home/molys/product/NER/chineseNER_ucas/ChineseNER/loader.py", line 32
SyntaxError: Non-ASCII character '\xef' in file /home/molys/product/NER/chineseNER_ucas/ChineseNER/loader.py on line 32, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by syw2014** [comment]
@molyswu I found you had run it with python2 but this project was developed with python3, you should make some changes that it can be run with python2

**Comment by syw2014** [comment]
@OYE93 This is OOV( out of vocabulary ) problem, and there are some methods to solve it like average , firtstly use the 'UNK' to replace the word which is OOV,  then train the mdoel

**Comment by OYE93** [comment]
Thanks, I used average.
