### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by yyHaker** [zjy-ucas/ChineseNER#22]
Hello! I run your code , but found errors below:
--------------------------------------
-------------------------------------

Traceback (most recent call last):
  File "F:/yyhaker/software/project/NamedEntityRecognition/src/ChineseNER/main.py", line 225, in <module>
    if __name__ == "__main__":
  File "D:\perhack\Anaconda3\envs\my_pytorch\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:/yyhaker/software/project/NamedEntityRecognition/src/ChineseNER/main.py", line 219, in main
    clean(FLAGS)
  File "F:/yyhaker/software/project/NamedEntityRecognition/src/ChineseNER/main.py", line 114, in train
    # create maps if not exist
NameError: name 'os' is not defined

----------------------------------
------------------------------------
I have install the os module, and it can run correctly! What's wrong with it?

**Comment by yyHaker** [comment]
Oh, god! When I "import tensorflow as tf" before "import os", the code can run correctly! But when I "import tensorflow as tf" after "import os", it can't run correctly and give the above error, what's wrong with it?

**Comment by qinya** [comment]
这个问题你解决了吗？

**Comment by KaqiKaqi** [comment]
@qinya 
我在这两行之间加了几行空行就行了
```
# encoding=utf8


import os
```

**Comment by weilonghu** [comment]
把# encoding=uft8去掉也可以，我不懂

**Comment by fhn0** [comment]
@yyHaker : thanks for your suggestions. same thing happened to me, and changing the import flow fixed it. not sure why!
