### ISSUE TITLE
运行时报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

### ISSUE THREAD

**Issue by icysnow123** [zjy-ucas/ChineseNER#35]
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    if __name__ == "__main__":
  File "C:\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 221, in main
    clean(FLAGS)
  File "main.py", line 187, in train

  File "main.py", line 87, in evaluate
    ner_results = model.evaluate(sess, data, id_to_tag)
  File "C:\pyproject\ChineseNER-master\utils.py", line 66, in test_ner
    eval_lines = return_report(output_file)
  File "C:\pyproject\ChineseNER-master\conlleval.py", line 284, in return_report
    counts = evaluate(f)
  File "C:\pyproject\ChineseNER-master\conlleval.py", line 74, in evaluate
    for line in iterable:
  File "C:\Python35\lib\codecs.py", line 711, in __next__
    return next(self.reader)
  File "C:\Python35\lib\codecs.py", line 642, in __next__
    line = self.readline()
  File "C:\Python35\lib\codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "C:\Python35\lib\codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

**Comment by ares89** [comment]
in utils.py line 55
 with open(output_file, "w") as f:

add encoding="utf8"

**Comment by LiXuanming** [comment]
编码问题，加上 #-*-coding:UTF-8-*-    即可

**Comment by icysnow123** [comment]
thank you
