### ISSUE TITLE
取作者全部数据集训练OK，但是取数据集中的前3000条训练数据为新的训练数据，验证及测试集数据不变，训练出错。

### ISSUE THREAD

**Issue by smartcatdog** [zjy-ucas/ChineseNER#77]
执行
```
mv example.train example.train.bak
head -2000 example.train.bak >> example.train
```
然后训练
`python main.py --train=True --clean=True`
报错：
```
Traceback (most recent call last):
  File "main.py", line 219, in main
    train()
  File "main.py", line 145, in train
    test_sentences, char_to_id, tag_to_id, FLAGS.lower
  File "ChineseNER/loader.py", line 110, in prepare_dataset
    tags = [tag_to_id[w[-1]] for w in s]
  File "ChineseNER/loader.py", line 110, in <listcomp>
    tags = [tag_to_id[w[-1]] for w in s]
KeyError: 'S-PER'
```
这是因为？

**Comment by Zhenguoshen** [comment]
我也是这个问题，但是我是自己的数据集出现这个问题，然后我按照你说的改了下作者训练数据集，也出现了这样的错误，你解决了吗

**Comment by hx-317** [comment]
这个问题怎么解决呢

**Comment by aSmallsheep** [comment]
> 执行
> 
> ```
> mv example.train example.train.bak
> head -2000 example.train.bak >> example.train
> ```
> 
> 然后训练
> `python main.py --train=True --clean=True`
> 报错：
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 219, in main
>     train()
>   File "main.py", line 145, in train
>     test_sentences, char_to_id, tag_to_id, FLAGS.lower
>   File "ChineseNER/loader.py", line 110, in prepare_dataset
>     tags = [tag_to_id[w[-1]] for w in s]
>   File "ChineseNER/loader.py", line 110, in <listcomp>
>     tags = [tag_to_id[w[-1]] for w in s]
> KeyError: 'S-PER'
> ```
> 
> 这是因为？

取作者数据集中的前3000条训练数据为新的训练数据，会不会出现标签覆盖不全的情况。

因为你取了作者训练集前3000条，导致训练集中未覆盖到“S-PER”这个实体类别，验证及测试集数据却有“S-PER”这个标签。
