### ISSUE TITLE
我修改了clean和train的False为True 然后运行报出name 'tf' is not defined的错误是什么情况

### ISSUE THREAD

**Issue by lengsihan** [zjy-ucas/ChineseNER#90]
Traceback (most recent call last):
  File "D:\ChineseNER-master\main.py", line 226, in <module>
    if __name__ == "__main__":
  File "D:\anaconda\envs\py36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\ChineseNER-master\main.py", line 220, in main
    clean(FLAGS)
  File "D:\ChineseNER-master\main.py", line 172, in train
    with tf.Session(config=tf_config) as sess:
  File "D:\ChineseNER-master\utils.py", line 172, in create_model
    model = Model_class(config)
  File "D:\ChineseNER-master\model.py", line 25, in __init__
    self.global_step = tf.Variable(0, trainable=False)
NameError: name 'tf' is not defined

进程已结束,退出代码1

**Comment by lengsihan** [comment]
已解决
